### PR TITLE
Custom log handler and driver

### PR DESCRIPTION
**Pull request by sixlive**
## Status

**WIP**

## Description
Adding a custom log handler and driver for Laravel's custom log channels.

```php
'channels' => [
    'honeybadger' => [
        'driver'  => 'custom',
        'via' => HoneybadgerLogDriver::class,
        'name' => 'asdf' // optional point of customization
    ]
]
```

## Related PRs
List related PRs against other branches:
[honeybadger-io/honeybadger-php - #66](https://github.com/honeybadger-io/honeybadger-php/pull/66)

## Todos
- [x] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)
- [x] Extract `LogHandler` to core `honeybadger-php` package
- [x] Update minimum version after https://github.com/honeybadger-io/honeybadger-php/pull/70 is merged

## Steps to Test or Reproduce
```bash
> git pull --prune
> git checkout <branch>
> vendor/bin/phpunit
```

## Screenshots
screenshot_2018-10-12 exception and uptime monitoring 360-degree coverage of errors outages and service degradation

### CODE REVIEW

**Comment by sixlive** [comment]
Monolog handler has been moved to the `honeybadger/honeybadger-php` package. - https://github.com/honeybadger-io/honeybadger-php/pull/70

**Comment by joshuap** [comment]
@sixlive can this be closed since implementation is happening on honeybadger-php?

**Comment by sixlive** [comment]
@joshuap no. I've updated this PR and removed the `LogHandler` but this still contains the `LogDriver` factory for Laravel integration.

**Comment by rmundel** [comment]
Is this still happening? (I hope so, please)

**Comment by sixlive** [comment]
@rmundel I'll make it happen!

**Comment by rmundel** [comment]
Sup bois. How is it going? :)

**Comment by rmundel** [comment]
Bump

**Comment by joshuap** [comment]
Hey @rmundel, we should be getting this one wrapped up soon. :)

**Comment by shalvah** [comment]
Hey @sixlive I've gone ahead to complete this. You already did the heavy lifting; I mostly just had to fix merge conflicts and update dependencies.😅 Also added some extra formatting improvements to the Monolog handler.

**Review by joshuap — COMMENTED** [review]
LGTM, although I'm no expert. :grin: @sixlive do you mind reviewing real quick?

**Comment by shalvah** [comment]
@joshuap no worries, I typically compile the changelog entries when tagging a new release.

**Comment by joshuap** [comment]
> @joshuap no worries, I typically compile the changelog entries when tagging a new release.

If the release is tagged in the PR that's OK, but our process is to update the changelog as a part of each PR. That's why there's an [unreleased heading](https://keepachangelog.com/en/1.0.0/). I also like to see the changelog messages when reviewing since they sometimes provide additional context. 👍

**Comment by shalvah** [comment]
Updated the changelog @joshuap

**Review by joshuap — APPROVED** [review]
This looks great to me. I'm good with shipping if you are @shalvah. :shipit:

**Comment by shalvah** [comment]
Released in 3.12.0 🎉

**Pull request merged**
