### PR TITLE
Add Laravel 6 support

### PR DESCRIPTION
**Pull request by jessarcher**
## Status

**WIP**

## Description
Add support for the newly released Laravel 6

## Todos
- [x] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

### CODE REVIEW

**Comment by jessarcher** [comment]
Build failing because testbench hasn't tagged a stable release yet for Laravel 6.0.

Not sure whether to wait for that, or adjust minimum stability requirements. I'll leave that call up to the maintainers :)

**Comment by sixlive** [comment]
WHOOP! I was planning on getting to this tomorrow but this is awesome! I'm doing some final testing of some features tomorrow so I'll get this deployed with that.

**Comment by kreitje** [comment]
Thanks!  Was just looking to submit a PR for this.

**Comment by jessarcher** [comment]
Thanks TJ! I've deployed it to my staging environment, so I'll be sure to let you know if I run into anything.

**Comment by sixlive** [comment]
Build passing! I still have a few things to test before tagging.

**Pull request merged**
