### PR TITLE
Adds support for Laravel 8

### PR DESCRIPTION
**Pull request by sixlive**
## Description
- Adds support for Laravel 8
- Drops PHPUnit pretty print formatter

Closes #57 
Closes #58

### CODE REVIEW

**Review by dacoto97 — APPROVED** [review]

**Comment by madsem** [comment]
Could this be merged today?

 Trying to `composer require honeybadger-io/honeybadger-laravel` but it fails :-(

**Comment by sixlive** [comment]
Yes, 100% today. Just want to get final signing from @joshuap

**Comment by madsem** [comment]
Thanks @sixlive you guys rock 👍

**Review by stympy — APPROVED** [review]
LGTM

**Review by joshuap — APPROVED** [review]
SHIPIT :shipit:

**Comment by sixlive** [comment]
I really didnt want to drop Laravel 7. To be honest the tooling was making it a nightmare but its all sorted!

**Comment by sixlive** [comment]
Tagged! https://github.com/honeybadger-io/honeybadger-laravel/releases/tag/v3.2.0

**Pull request merged**
