### PR TITLE
Target Laravel 8 in CI

### PR DESCRIPTION
**Pull request by joshuap**
We had a customer ask if we support Laravel 8 yet. I'm thinking this might tell me the answer. :) 

Edit: just noticed #57—maybe we need both of these PRs combined.

### CODE REVIEW

**Comment by joshuap** [comment]
I guess this may be a bit more involved than updating tested versions. @sixlive can you take a look when you get the chance?

**Comment by rmundel** [comment]
> We had a customer ask if we support Laravel 8 yet. I'm thinking this might tell me the answer. :)
> 
> Edit: just noticed #57—maybe we need both of these PRs combined.

Two customers now. Bump!

**Comment by sixlive** [comment]
I'll have this taken care of tonight or tomorrow morning!

**Comment by sixlive** [comment]
I'm battling some really weird CI/Dependency issues, trying to wrestle my way through them

**Comment by sixlive** [comment]
Closing in favor of https://github.com/honeybadger-io/honeybadger-laravel/pull/59

**Pull request closed without merging**
