### PR TITLE
Move to Laravel 7

### PR DESCRIPTION
**Pull request by damcclean**
## Status

**READY**

## Description
Upgraded the `illuminate/console` and `illuminate/support` packages to support Laravel 7.

## Todos
- [x] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

### CODE REVIEW

**Comment by sixlive** [comment]
Was there a bump in testbench to match the new framework version?

**Comment by damcclean** [comment]
> Was there a bump in testbench to match the new framework version?

Just had a look at that wondering why my Travis builds were failing. Looks like there's a v5 release that supports Laravel v7 but this package is currently on 3.5. 

Is this to support the older versions of PHPUnit or do you think it would be safe to upgrade Testbench?

**Comment by sixlive** [comment]
Everything can be updated to support 7. I’m going to cut a major Version as this drops support for 6.

**Comment by damcclean** [comment]
> Everything can be updated to support 7. I’m going to cut a major Version as this drops support for 6.

Awesome! Just updated testbench now and Travis seems to be green, which is always a good sign 😂

**Comment by sixlive** [comment]
Nice! I’ll merge and tag when I get home from work!

**Comment by sixlive** [comment]
Thank you so much for working though the PR!!!

**Comment by damcclean** [comment]
> Thank you so much for working though the PR!!!

Yeah, no problem!

**Comment by jhoff** [comment]
Any status on this? Currently the last package blocking our upgrade.

**Comment by damcclean** [comment]
@jhoff all that needs to happen for this to support L7 is for this pull request to be merged and for a release to be tagged.

Were waiting for @sixlive to do this.

**Comment by sixlive** [comment]
I'm so sorry, I caught a cold and totally lost track of this.

**Comment by jhoff** [comment]
Thanks @sixlive!

**Comment by jhoff** [comment]
Sorry for the poke @sixlive, but will this be tagged as well?

**Comment by sixlive** [comment]
I merged, got interrupted and totally forgot to tag. Just tagged it!!

**Pull request merged**
