### PR TITLE
Add installer command

### PR DESCRIPTION
**Pull request by sixlive**
## Status

**READY**

## Description
This PR adds an installer command that is able to perform the following actions for both Laravel and Lumen:

* Optionally publish the configuration file
* Add the `HONEYBADGER_API_KEY` with the provided API key to the `.env` file
* Add a placeholder `HONEYBADGER_API_KEY` to the `.env.example` file
* Optionally send a test exception to Honeybadger based on the provided API key
* Some fixes for issues identified by Scrutinizer

## Related PRs
n/a
## Todos
- [x] Tests
- [ ] Documentation
- [x] Changelog Entry (unreleased)
- [x] Fix Scrutinizer concerns

## Steps to Test or Reproduce
```bash
> git pull --prune
> git checkout <branch>
> vendor/bin/phpunit
```

1. Inside a Laravel or Lumen application install the package
1. Add the service provider (Lumen or Laravel 5.5 only)
2. Run `php artisan honeybadger:install`

## Screenshots
screen shot 2018-08-20 at 9 02 10 am
screen shot 2018-08-20 at 8 58 05 am
screen shot 2018-08-20 at 9 07 23 am

### CODE REVIEW

**Comment by joshuap** [comment]
@sixlive this is pretty cool! Here are a few thoughts:

1. I tried running the command and hitting "enter" for the default values. When it asked for the API key, it let me continue with a blank value, and it said a test exception was sent (even though it must have been rejected by our API). The `honeybadger:test` command appears to return an error when there is no API key, which is correct.
2. Not sure if this is possible, but *if* we could auto-inject the reporting code into `app/Exceptions/Handler.php`, then this install command would not require any additional steps. Otherwise it's a little awkward to say "run the install command, but then also manually edit this one file". Thoughts on this?
3. Can we add a welcome message at the end? Here's the welcome message from our Ruby gem (I'll edit one for Laravel below): https://github.com/honeybadger-io/honeybadger-ruby/blob/master/lib/honeybadger/cli/test.rb#L230

```
⚡ --- Honeybadger is installed! -----------------------------------------------
Good news: You're one deploy away from seeing all of your exceptions in
Honeybadger. For now, we've generated a test exception for you:

    #{notice_url}

If you ever need help:

    - Check out the documentation: https://docs.honeybadger.io/lib/php/index.html
    - Email the 'badgers: support@honeybadger.io

Most people don't realize that Honeybadger is a small, bootstrapped company. We
really couldn't do this without you. Thank you for allowing us to do what we
love: making developers awesome.

Happy 'badgering!

Sincerely,
Ben, Josh and Starr
https://www.honeybadger.io/about/
⚡ --- End --------------------------------------------------------------------
```

If we can include the notice URL, great. Just remove that part if not.

**Comment by sixlive** [comment]
@joshuap This is mostly good to go but I wanted to get some feedback on the success messaging. 

demo

screenshot

Between the success/fail output of each task and the success message if feels like its a lot of output. I'd like to maybe find a happy medium. 

We also need to better define when the success message shows. Which tasks are we willing to let fail and still show the success message?

**Comment by joshuap** [comment]
> We also need to better define when the success message shows. Which tasks are we willing to let fail and still show the success message?

If it's possible for `.env` or `.env.example` to not exist in some projects, we could let those fail, but then there wouldn't be an API key configured, right? There should always be an error output if the test fails.

The minimum required steps would be 1) add config (with API key), 2) send test.

> Between the success/fail output of each task and the success message if feels like its a lot of output. I'd like to maybe find a happy medium.

What are you thinking? Shorter success message? I'm thinking that we don't really need to prompt to send the test error--we *always* want the test error to be sent, because that's what allows the onboarding process in our UI to continue (it waits for the test error to arrive).

I'm open to any suggestions you have about how you as a user would like the interface/output to work, though.

**Comment by sixlive** [comment]
To make things easier I went ahead and made all steps required in sequential order.

screenflow

**Comment by joshuap** [comment]
@sixlive looks good to me. Let's :shipit:

**Pull request merged**
