### PR TITLE
feat: add support for eu endpoints with install command

### LINKED ISSUE #137: Changes for EU endpoint
The installer command should have an optional flag that sets the endpoint to https://eu-api.honeybadger.io/ when generating the configuration file. See https://github.com/honeybadger-io/honeybadger-ruby/pull/584 for the similar change that was made to the Ruby gem.

https://github.com/honeybadger-io/honeybadger-laravel/blob/b96932cb21f7bf98e55775746ca83faff7425986/src/Commands/HoneybadgerDeployCommand.php#L51 also needs to be updated to use the EU host instead of being hard-coded to api.honeybadger.io.

### PR DESCRIPTION
**Pull request by subzero10**
## Status
**READY**

## Description
- Adds configurable endpoints in config file.
- Adds optional parameters to _install_ command for endpoint and app endpoint.

The install command for HB EU becomes:
```
php artisan honeybadger:install API_KEY --endpoint https://eu-api.honeybadger.io --appEndpoint https://eu-app.honeybadger.io
```

Closes #137.

## Todos
- [x] Tests
- [x] Manual Testing
- [x] Documentation - https://github.com/honeybadger-io/docs/pull/546

### CODE REVIEW

**Review by stympy — CHANGES_REQUESTED** [review]
Please make the default API endpoint https://api.honeybadger.io/ instead of https://api.honeybadger.io/v1 and omit the /v1 from the --endpoint option so that the --endpoint option matches the --appEndpoint option.

Also, please remove the --eu option.

**Comment by subzero10** [comment]
> Please make the default API endpoint https://api.honeybadger.io/ instead of https://api.honeybadger.io/v1 and omit the /v1 from the --endpoint option so that the --endpoint option matches the --appEndpoint option.

Does that it mean it will work even without the `v1` in the url? I didn't know that.

> Also, please remove the --eu option.

Oh shoot, I thought this would be a nice touch, because the command becomes quite long and increases the chances of typing errors. I can remove it though.

**Comment by stympy** [comment]
> > Please make the default API endpoint https://api.honeybadger.io/ instead of https://api.honeybadger.io/v1 and omit the /v1 from the --endpoint option so that the --endpoint option matches the --appEndpoint option.
> 
> Does that it mean it will work even without the `v1` in the url? I didn't know that.

No, the requested URL must include /v1, but that should be appended to the API URL — e.g., `API_URL . '/v1/deploys'` instead of `API_URL . '/deploys'`.

> 
> > Also, please remove the --eu option.
> 
> Oh shoot, I thought this would be a nice touch, because the command becomes quite long and increases the chances of typing errors. I can remove it though.

It's not a bad a idea, but I don't want to have to revisit adding more options should we deploy to more regions in the future.

**Comment by subzero10** [comment]
> No, the requested URL must include /v1, but that should be appended to the API URL — e.g., API_URL . '/v1/deploys' instead of API_URL . '/deploys'.

👍 

> It's not a bad idea, but I don't want to have to revisit adding more options should we deploy to more regions in the future.

👍

**Review by stympy — APPROVED** [review]

**Pull request merged**
